# -*- coding: utf-8 -*-
"""Ejemplo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15RbsfxnNiFgqGzMaxC46oic7H_xtcAQW
"""

def suma(x,y):
  return x+y
print(suma(3,4))
print(suma("Hola","Mundo"))